version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres_guild
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guild_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: rails_guild
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - frontend
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: guild_development

  frontend:
    build:
      context: ./frontend
    container_name: angular_guild
    command: ng serve --host 0.0.0.0 --disable-host-check
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"

volumes:
  pgdata:
